### ISSUE TITLE
 Method EasyPanel\Commands\Actions\MakeCRUDConfig::qualifyModel does not exist.

### ISSUE THREAD

**Issue by GuerfiHamza** [rezaamini-ir/laravel-easypanel#11]
Hello,
When i try to run php artisan panel:config user -m User i get this error

` Method EasyPanel\Commands\Actions\MakeCRUDConfig::qualifyModel does not exist.`
can you help please ?

**Comment by rezaamini-ir** [comment]
Hello 
I have fixed this problem in `1.4.2` version.
Please update the package with composer and `--no-cache` flag:
```
composer update rezaamini-ir/laravel-easypanel
```
Then use the new command style :
```
php artisan panel:config [Model]
```

**Comment by elchroy** [comment]
I have this same problem, with my Laravel 6 app. I downgraded from 1.5.1 to 1.4.2 but I still face the same error. Please help, thanks

**Comment by rezaamini-ir** [comment]
Hi @elchroy could you please tell me the version of your application?
the exact version.

**Comment by shankar-bavan** [comment]
I got same issue.
laravel/framework: "^7.24",
rezaamini-ir/laravel-easypanel: "^1.5",
